---
apiVersion: v1
kind: Service
metadata:
  name: node-app-test
  namespace: athena-dev
  labels:
    app: node-app-test
spec:
  selector:
    app: node-app-test
  type: LoadBalancer
  ports:
    - port: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-app-test
  namespace: athena-dev
  labels:
    app: node-app-test
spec:
  selector:
    matchLabels:
      app: node-app-test
  template:
    metadata:
      labels:
        app: node-app-test
    spec:
      containers:
        - name: node-app-test
          image: us.icr.io/ddp-athena-dev/node-app-test
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: default-us-icr-io
